### ISSUE TITLE
Client: AuthProvider cannot be updated while rendering a different component

### ISSUE THREAD

**Issue by KevinGus** [jbt-it/neomdb#108]
![image](https://user-images.githubusercontent.com/57221059/121664953-512aad80-caa8-11eb-95fb-10fa39eb3885.png)

**How to recreate this problem:**

- Login to the neoMDB
- Reload a Page (no matter which page you´re on)

Error occurse on following OS: 

- Windows
- Ubuntu 18.04

**Comment by LennartRukower** [comment]
This bug was fixed with #115
