### ISSUE TITLE
Client: Projectoverview

### ISSUE THREAD

**Issue by johannesfbraun** [jbt-it/neomdb#165]
- current projects to apply for
   - user can click on project and is redirected to the project details page 
- project you are working in
   - user can click on project and is redirected to the project details page
- NO sales graphic/diagram, not in scope yet
- List of all projects with (Projektname, BRanche, Unternehmensname, Kernkompetenz, start date, end date, number of BT, status of project)
   - user can click on project and is redirected to the project details page
   - the list can be filtered by Kernkompetenz, timeframe (from... to...), and free text
   - the liste can be sorted by every column (desc/asc)

**Comment by LennartRukower** [comment]
- user can click on a project an is redirected to the project details page
   - projectlist can be filtered by Kernkompetenz, Timeframe, and free text
