### ISSUE TITLE
Server: Addition to API calls for internal Projects in Traineesection

### ISSUE THREAD

**Issue by Prschmidt** [jbt-it/neomdb#271]
For the Traineesection some additional information needs to be called in the api "getInternalProjectsOfGeneration" in the TraineeController.

This Information is needed for the Traineesection:
- internesprojektID
- generation
- projektname
- kickoff
- AngebotbeiEV
- ZPgehalten
- Apgehalten
- DLbeiEV

**Comment by jbt-it** [comment]
Possible duplicate to #130?

**Comment by jbt-it** [comment]
Already done
