### ISSUE TITLE
Fix profile page display

### ISSUE THREAD

**Issue by LennartRukower** [jbt-it/neomdb#328]
When you visit your profile page the edit buttons are not displayed:
![image](https://github.com/jbt-it/neomdb/assets/45009167/df716bda-1abe-4068-bb91-3f76027fe25b)

When you zoom out (in image 90% zoom), you can see the edit buttons:
![image](https://github.com/jbt-it/neomdb/assets/45009167/3d80c394-419b-42d6-8a30-5e6d537b43c9)

When you visit profile pages of other members, you can see the edit buttons (if you have the specific persmissions):
![image](https://github.com/jbt-it/neomdb/assets/45009167/2cd24a9e-6b31-4a2d-bf28-8a53932e4993)

The edit buttons be consistently displayed.

**Comment by JanMueller31** [comment]
Closed due to previous fix
