### ISSUE TITLE
Client: Project details admin

### ISSUE THREAD

**Issue by jbt-it** [jbt-it/neomdb#341]
- If the user has “(21) Projektbewerbungen”: See the applications 

- the user can with permission“(19) Projektausschreibung”: edit the project, create a nextcloud folder for it, cancel it 

- the user can with permission “(21) Projektbewerbungen”: look at the individual applications, look at the old applications, can create a shareable link for eveybody 

- the user can with permisssion “(22) Projektabrechnung”: can satrt billing phase if BT and expenses are filled im, and at the start of the billing phase a bill is created for the RL-F&R in pdf format and sent to finanzen@, this pdf can be generated again

**Comment by LennartRukower** [comment]
Already specified in #167
