### ISSUE TITLE
Server: Add data to memberController

### ISSUE THREAD

**Issue by LennartRukower** [jbt-it/neomdb#71]
- The member is not able to update "_vertiefungen_" and "_engagement_". 
- A member with special permissions is not able to update "_jbt-email_". 
- "_Sprachen_" are not available (it is not possible yet, to display the different languages of a member).

**Comment by christophtrybek** [comment]
* Members should not be allowed to change the field "engagement" by themselves

**Comment by LennartRukower** [comment]
I realized that it is not possible yet, to retrieve "Mentees" and "Mentor" of a member.

**Comment by LennartRukower** [comment]
@christophtrybek, are you working on this issue? If not, I can do it.
